### ISSUE TITLE
Fail to install deepredmt.

### ISSUE THREAD

**Issue by Galaxy-228** [aedera/deepredmt#1]
Hi~
When i type 'pip install -U "deepredmt @ git+https://github.com/aedera/deepredmt.git" ', an error showed up followed:
![图片](https://user-images.githubusercontent.com/53716512/229715973-20daaa90-27d0-4669-8186-641ea7f2bec9.png)
Thanks so much.

**Comment by aedera** [comment]
Hi,

It seems that there is a problem with the network connection or the installation is being done behind a proxy.

Please check that the repository can be accessed from the network, for example, by cloning it using this command:

```
$ git clone https://github.com/aedera/deepredmt.git
```

If this fails, you may want to check [this](https://stackoverflow.com/questions/70700776/unable-to-connect-to-git-server-via-http-http-2-stream-0-was-not-closed-cleanly).

**Comment by aedera** [comment]
I will close this issue for now, since it seems that there is not an issue of deepredmt per se.
