### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by bimalkc-design** [aedera/deepredmt#3]
This step may take up to 5 minutes.

WARNING: Skipping yellowbrick as it is not installed.
WARNING: Skipping xarray-einstats as it is not installed.
WARNING: Skipping imbalanced-learn as it is not installed.
WARNING: Skipping datascience as it is not installed.
WARNING: Skipping albumentations as it is not installed.
WARNING: Skipping arviz as it is not installed.
WARNING: Skipping pymc3 as it is not installed.
  Running command git clone --filter=blob:none --quiet https://github.com/aedera/deepredmt.git /tmp/pip-install-8

**Comment by bimalkc-design** [comment]
Note: The higher a score is, the more likely a site is edited.

Traceback (most recent call last):
  File "/usr/local/bin/deepredmt", line 8, in <module>
    sys.exit(deepredmt())
  File "/usr/local/lib/python3.10/dist-packages/deepredmt/cli.py", line 34, in deepredmt
    _predict_from_fasta(fin)
  File "/usr/local/lib/python3.10/dist-packages/deepredmt/cli.py", line 13, in _predict_from_fasta
    wins, preds = predict_from_fasta(fasin)
  File "/usr/local/lib/python3.10/dist-packages/deepredmt/predict.py", line 83, in predict_from_fasta
    model = tf.keras.models.load_model(tf_model, compile='False')
  File "/usr/local/lib/python3.10/dist-packages/keras/src/saving/saving_api.py", line 199, in load_model
    raise ValueError(
ValueError: File format not supported: filepath=/usr/local/lib/python3.10/dist-packages/deepredmt/./model/210520.tf. Keras 3 only supports V3 `.keras` files and legacy H5 format files (`.h5` extension). Note that the legacy SavedModel format is not supported by `load_model()` in Keras 3. In order to reload a TensorFlow SavedModel as an inference-only layer in Keras 3, use `keras.layers.TFSMLayer(/usr/local/lib/python3.10/dist-packages/deepredmt/./model/210520.tf, call_endpoint='serving_default')` (note that your `call_endpoint` might have a different name).
Predictions finished!
Below the first 10 predictions are shown.
Pos  Upstream  Target  Downstream  Score

**Comment by aedera** [comment]
Hello,

I have updated deepredmt to address the problem.

Please feel free to reopen this issue if the problem persists.

Best,
